FROM golang:1.24.2-bookworm as build

WORKDIR /go/src/github.com/balena-go-hello-world

COPY src/ src/

RUN go mod init && go build /go/src/github.com/balena-go-hello-world/src/server.go

FROM debian:bookworm-slim

WORKDIR /go/src/github.com/balena-go-hello-world

COPY --from=build /go/src/github.com/balena-go-hello-world/server .

COPY views/ views/

CMD [ "./server" ]
