FROM resin/%%RESIN_MACHINE_NAME%%-golang:1.9-stretch AS build

ENV INITSYSTEM on

# RUN apt-get -q update && apt-get install -yq --no-install-recommends \
# 	build-essential \
# 	&& apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /go/src/github.com/resin-io-projects/app

COPY /app ./

RUN go build

FROM resin/%%RESIN_MACHINE_NAME%%-debian:stretch

COPY --from=build /go/src/github.com/resin-io-projects/app/ .

CMD ./app
